### PR TITLE
Ability to configure client_id and client_secret on getAccessToken

### PR DESCRIPTION
**Pull request by dmorina**
The idea is to allow client credential configuration at a later point in time right when calling getAccessToken(), for example if the successful authentication returns new client_id and client_secret

### CODE REVIEW

**Comment by dmorina** [comment]
let me know what you think about this, thanks

**Comment by joaogranado** [comment]
Hey @dmorina! Sorry for the late response. Could you provide an use case or some example of this implementation? Thanks.

**Comment by dmorina** [comment]
Hey @joaogranado thanks for the reply
So a use case would be when you dont have the client credentials yet i.e say you generate them after successful two-factor auth, and once you have the new client_secret client_id we use them to get the oauth2 tokens

Sample code with basic auth initially:
```
 Authentication.login(vm.username, vm.password).then(function success(data, status) {
          var user = {username:data.data.username, password:vm.password};
          var post_config = {client_id: data.data.client_id, client_secret:data.data.client_secret};
          OAuth.getAccessToken(user, null, post_config);
}
```

Does it make sense, or is there a different way to achieve this here?

Thanks

**Comment by joaogranado** [comment]
@dmorina as far as I understand you're creating the client credentials at runtime/programmatically and is generally not considered to be a good practice. The OAuth application should be registered on the service's website manually and your application should only use that generated `client_id` and `client_secret`.

That said, I believe this is out of the scope for this library so, respectfully, we won't be able to merge this PR.

**Comment by dmorina** [comment]
Alright, thanks

**Pull request closed without merging**
