### PR TITLE
Fix removeToken() issue

### PR DESCRIPTION
**Pull request by rllola**
A quick fix for issue  #33

### CODE REVIEW

**Comment by ruipenso** [comment]
Hi @rllola.

This issue will be fixed with #25. But, while we're waiting for Angular 1.4 stable we can merge your PR.

Just squash the 2 commits.

Thanks.

**Comment by rllola** [comment]
Hi @ruipenso 

Done.

Thanks.

**Comment by ruipenso** [comment]
@rllola Can you please remove the `dist` files?

**Comment by rllola** [comment]
@ruipenso Done.

**Comment by ruipenso** [comment]
Landed on commit eb6be56.

Thank you.

**Pull request closed without merging**
